global:
  resolve_timeout: 5m

route:
  receiver: 'telegram'
  group_wait: 5s
  group_interval: 5s
  repeat_interval: 1h

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: '8290668777:AAGIKBPVEOFUNy_FThgpy3aVDKN1J5WYDwE'
        chat_id: '498634016'
        parse_mode: 'HTML'
        message: |
          🚨 <b>{{ .Status | toUpper }}</b>: {{ .CommonLabels.alertname }}
          🔥 <b>Instance</b>: {{ .CommonLabels.instance }}
          💬 <b>Summary</b>: {{ .CommonAnnotations.summary }}
          📋 <b>Description</b>: {{ .CommonAnnotations.description }}
          🕒 <b>Time</b>: {{ .StartsAt }}